blank_issues_enabled: true
contact_links:
  - name: Contribution guidelines
    url: https://source.tube/pmurad/awesome-indieweb/src/branch/main/CONTRIBUTING.md
    about: Please read the guidelines before adding, updating, or removing an entry.
